# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"
  config.vm.box_check_update = false

  # Turn off vbguest if installed as bento has guest additions installed
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
