# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Turn off vbguest as basebox has guest additions installed
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.box = "geerlingguy/rockylinux8"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :hosts, :sync_hosts => true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "nodejs" do |app|
    app.vm.hostname = "nodejs.test"
    app.vm.network :private_network, ip: "192.168.4.4"
  end

  # Application server 2
  config.vm.define "drupal" do |app|
    app.vm.hostname = "drupal.test"
    app.vm.network :private_network, ip: "192.168.4.5"
  end

end
